#!/usr/bin/env python3
"""Generate the small application-produced OOXML fixtures.

This script is optional developer tooling. CI consumes the checked-in files and
does not need these Python packages installed.
"""

from __future__ import annotations

from pathlib import Path

from docx import Document
from openpyxl import Workbook
from pptx import Presentation


ROOT = Path(__file__).resolve().parents[3]
FILES = ROOT / "tests" / "fixtures" / "files"


def generate_docx() -> None:
    output = FILES / "docx" / "python-docx-basic.docx"
    output.parent.mkdir(parents=True, exist_ok=True)

    document = Document()
    props = document.core_properties
    props.author = "oxdoc"
    props.title = "oxdoc python-docx fixture"
    props.subject = "Redistributable DOCX parser fixture"

    section = document.sections[0]
    section.header.paragraphs[0].text = "DOCX generated header"
    section.footer.paragraphs[0].text = "DOCX generated footer"

    document.add_heading("Oxdoc DOCX Application Fixture", level=1)
    document.add_paragraph("Body text with ampersand & comma, generated by python-docx.")

    table = document.add_table(rows=2, cols=2)
    table.cell(0, 0).text = "Field"
    table.cell(0, 1).text = "Value"
    table.cell(1, 0).text = "Producer"
    table.cell(1, 1).text = "python-docx"

    document.save(output)


def generate_xlsx() -> None:
    output = FILES / "xlsx" / "openpyxl-basic.xlsx"
    output.parent.mkdir(parents=True, exist_ok=True)

    workbook = Workbook()
    workbook.creator = "oxdoc"
    workbook.properties.title = "oxdoc openpyxl fixture"
    workbook.properties.subject = "Redistributable XLSX parser fixture"

    sheet = workbook.active
    sheet.title = "Data"
    rows = [
        ("Name", "Value", "Notes"),
        ("Ada", 42, "plain"),
        ("Quote, comma", True, 'He said "hi"'),
        ("Line break", 3.5, "alpha\nbeta"),
    ]
    for row in rows:
        sheet.append(row)

    hidden = workbook.create_sheet("Hidden")
    hidden.sheet_state = "hidden"
    hidden["A1"] = "not selected"

    workbook.save(output)


def generate_pptx() -> None:
    output = FILES / "pptx" / "python-pptx-basic.pptx"
    output.parent.mkdir(parents=True, exist_ok=True)

    presentation = Presentation()
    presentation.core_properties.author = "oxdoc"
    presentation.core_properties.title = "oxdoc python-pptx fixture"
    presentation.core_properties.subject = "Redistributable PPTX parser fixture"

    title_slide = presentation.slides.add_slide(presentation.slide_layouts[0])
    title_slide.shapes.title.text = "Oxdoc PPTX Application Fixture"
    title_slide.placeholders[1].text = "Generated by python-pptx"

    content_slide = presentation.slides.add_slide(presentation.slide_layouts[1])
    content_slide.shapes.title.text = "Slide Two"
    body = content_slide.placeholders[1].text_frame
    body.text = "First bullet"
    second = body.add_paragraph()
    second.text = "Second bullet with & entity text"

    presentation.save(output)


def main() -> None:
    generate_docx()
    generate_xlsx()
    generate_pptx()


if __name__ == "__main__":
    main()
